language: node_js
node_js:
- 4
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- npm run buildAvalon
script:
- npm run build
- npm run sauce
addons:
  code_climate:
    repo_token: cecb8ec105dc8e4b3f298312502f078a646f46ff
after_success:
- npm run coveralls &  codeclimate-test-reporter < lcov.info
env:
  global:
    secure: ChpR1hjUP4enUX+C0PhZE9VO4UAZ3UIX9hKeYVUUn9pqAcDBi+1e5uTFHy15f9sGiZPm+iYubtGGN3I9UH5zNydTM9nXbhsjJPXsBRvUlBa5HBaKF/YucZBc6pTGgSSPnux4+ee7PY8dv0byLxvKDvEnbcHG6Wy99MshI+zrbu7RPoNfKtlHyDV8jUnPDCZy3+3yRp51GEw+qYyRr3PUJMODt6ZWGEinVezF0za3zI+vTioN/dNW662Jjk/01mETxPW/K4jEEk40vLgqHvIYm9KjFwaR3HeEnq6fZoW5TcKYvbeKuKFulc5TJLe8sNth3C+4KMg7fE3nOIWOiVTcUpyAgVA0G9ZEgr5AsxjHfriEKnvvIGl8V6OHRZdIZIXi0neeoa601aH5w5t4L8iZJrkSq5EJkFVEyQGTVWOA2DmHK5mxu3b6syD38VVL3iaIDz3uDM14NxskHrb4/39oGcuAEX4ZLFxcndT9v881sTSeGVV7y+c8LO3pemBKyCpKKRMjG6KIClzq/vmr5soP0CIBFROa1LJ5EdNW5+kNCzuN2p4xv8LVMekaftlaqhjq72CoX34U8N3qSMebNdVOTxCpeC3gKVewqglVq5QJUO1JZcrBS0S2P78tHeOA9vkJHYJdO97eXH/aqAktkaw99iRXKPBUpt+3xo7d2BrrvYA=
    secure: "hUiKryqMMLGyFgRu3pK7LNJcQUduRr39F+/YHPRybvlG9BcG+36K8dvXLOFWYsg1GdKysXjo9v6aTEfTLo3rYhSg5sE1kF9JFyj0N/7gvqBDD2m4Qj67tH0WEgACAwmSva9KbSoxcy9fWfd+o5+fzJMtu49WKkf8kyMnnBbFJqQgRBPbp7lNU3ozQ6+q9dfu5uo/Ew1v70TaGlwcpYKFfS027Lugw/iffLaDh5jmL5+nI5yiH5hQhJa+ng4I+LIPMcPIGmaDUwD52QaSJberSCPUCkSfAwZuUERoLGg/hWG9Z74fBoSQqwBep0K+COJvl025a8oC3rwTR+a15yAB4MoDxWz7dRyA9A88Y8QaojIPSzpAPF+fu7lEuNz35Vbr+6lpmWAYI3NpylONpKyQNih5O1Bpr//5dc7I8dz299EjgaDL0rQlmoDTsoeh2Di++z/cR+MYZUqmGs9JPWt4QF1I81E4s7D+EH61buavvCSG/nmw+4E1Yxs3WDE+u8bIeZs0eXhAR1Ao3YzZZl/b7Md7cFqqON/xhZZx2XNA+IoThs3eAuMWvwv+Tdox8eL++zs9u0Luw4CCIPnuz4axY0iVpGSzwqd+16Bmy+BoEZ3tr4dUR2wKY6lzXOXILPhzgNkeAoO28Y92sLjJxIS4lHiKJabd2L5CxILJe6w8FiM="