language: node_js
node_js:
  - 4
cache:
  directories:
    - node_modules
before_script:
  - phantomjs --help
before_install:
  - sudo apt-get install google-chrome-stable
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - master
after_success:
  - bash <(curl -s https://codecov.io/bash)